config/routes.rb
Iotagive::Application.routes.draw do
  resources :impacts

  devise_for :users

 get 'about' => 'pages#about'
 root :to => 'impacts#index'

end

app/models/impact.rb
class Impact < ActiveRecord::Base
  attr_accessible :description, :image


validates :description, presence: true
validates :user_id, presence: true
validates_attachment :image, presence: true,
							 content_type: { content_type: ['image/jpeg', 'image/jpg', 'image/png', 'image/gif'] },
							 size: { less_than: 5.megabytes }


	belongs_to :user
	has_attached_file :image, styles: { medium: "320x240>"}
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name
  # attr_accessible :title, :body

  has_many :impacts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/impacts_controller.rb
class ImpactsController < ApplicationController
  before_filter :authenticate_user!, except: [:index]

  # GET /impacts
  # GET /impacts.json
  def index
    @impacts = Impact.order("created_at desc")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @impacts }
    end
  end

  # GET /impacts/1
  # GET /impacts/1.json
  def show
    @impact = Impact.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @impact }
    end
  end

  # GET /impacts/new
  # GET /impacts/new.json
  def new
    @impact = current_user.impacts.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @impact }
    end
  end

  # GET /impacts/1/edit
  def edit
    @impact = current_user.impacts.find(params[:id])
  end

  # POST /impacts
  # POST /impacts.json
  def create
    @impact = current_user.impacts.new(params[:impact])

    respond_to do |format|
      if @impact.save
        format.html { redirect_to @impact, notice: 'Impact was successfully created.' }
        format.json { render json: @impact, status: :created, location: @impact }
      else
        format.html { render action: "new" }
        format.json { render json: @impact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /impacts/1
  # PUT /impacts/1.json
  def update
    @impact = current_user.impacts.find(params[:id])

    respond_to do |format|
      if @impact.update_attributes(params[:impact])
        format.html { redirect_to @impact, notice: 'Impact was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @impact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /impacts/1
  # DELETE /impacts/1.json
  def destroy
    @impact = current_user.impacts.find(params[:id])
    @impact.destroy

    respond_to do |format|
      format.html { redirect_to impacts_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/impacts_helper.rb
module ImpactsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/impacts/_form.html.erb
<%= simple_form_for(@impact, html: { class: "form-horizontal"}) do |f| %>
  <%= f.error_notification %>
  <%= f.full_error :image_file_size, class: "alert alert-error" %>
  <%= f.full_error :image_content_type, class: "alert alert-error" %>

  	<%= f.input :image, label: "Upload an image" %>
    <%= f.input :description, as: :text, input_html: { rows: "3" } %>
  

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/impacts/_impact.html.erb
 <div class="box">
   <%= link_to (image_tag impact.image(:medium)), impact %>
   <p class="description">
   <%= impact.description %>
   </p>
   <p>
   	<strong>
   		Posted by <%= impact.user.name %>
   	</strong>
   </p>
   <% if current_user == impact.user %>
   <p>
   <%= link_to 'Edit', edit_impact_path(impact) %>
   <%= link_to 'Destroy', impact, method: :delete, data: { confirm: 'Are you sure?' } %>
   </p> 
   <% end %>
  </div> 
 

app/views/impacts/edit.html.erb
<h1>Editing impact</h1>

<%= render 'form' %>

<%= link_to 'Show', @impact %> |
<%= link_to 'Back', impacts_path %>

app/views/impacts/index.html.erb
<%= render 'pages/home' %>

<div id="impacts">
	<%= render @impacts %>
</div>

app/views/impacts/new.html.erb
<h1>New impact</h1>

<%= render 'form' %>

<%= link_to 'Back', impacts_path %>

app/views/impacts/show.html.erb
<div class="row">
	<div class="span6 offset3">
		<div class="well">
		<%= image_tag @impact.image %>
	<p>
  		<b>Description:</b>
  		<%= @impact.description %>
	</p>
	<p>
  		<%= @impact.user.name %>
	</p>
	<% if current_user == @impact.user %>
	<%= link_to 'Edit', edit_impact_path(@impact) %> |
	<% end %>
	<%= link_to 'Back', impacts_path %>
		</div>
	</div>
</div>

app/views/layouts/_footer.html.erb
<div class='footer'>
	<small>
		<%= link_to "Iotagive", "http://iotagive.com"%>
		by <%= link_to "Tim Duymich", "www.facebook.com/timothyduymich"%>
	</small>
	<small> 
		<li><%= link_to "About", about_path %></li>
	</small>
	</div>	

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
    <a class="brand" href="#"> <img src="/images/logosmall.png"></a>
      <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
 
      <!-- Be sure to leave the brand out there if you want it shown -->
      
 
      <!-- Everything you want hidden at 940px or less, place within here -->
      <div class="nav-collapse collapse">
      	<ul class="nav">
      		<li><%= link_to "Home", root_path %> <img src"/images/homebutton.png"></li>
		    </ul>
		<ul class="nav pull-right">
        <% if user_signed_in? %>
         <li><%= link_to "Upload", new_impact_path, class: "btn btn btn-primary" %></li>
         <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
          <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
          <% else %>
      		<li><%= link_to "Login", new_user_session_path %></li>
		      <% end %>
    </ul>
        <!-- .nav, .navbar-search, .navbar-form, etc -->
      </div>
 
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	<title>Iotagive</title>
	<%= stylesheet_link_tag    "application", :media => "all" %>
	<%= javascript_include_tag "application" %>
	<%= csrf_meta_tags %>

	<%= render "layouts/header" %>
	
	<div class="container">
		<% flash.each do |name, msg| %>
			<%= content_tag(:div, msg, class: "alert alert-#{name}") %>
		<% end %>
		<%= yield %>
	<%= render "layouts/footer" %>	
	</div>

	</body>

</html>

app/views/pages/_home.html.erb
<% unless user_signed_in? %>	

<div class="hero-unit">
<center><h1>Welcome!</h1>
Iotagive is a place where users can share and like photographs while raising money for non-profits
	<p><%= link_to  "Sign Up Now!" , new_user_registration_path , class: "btn btn-primary btn-large" %>
</p>
</center>
</div>
<% end %>

app/views/pages/about.html.erb
<h1>About</h1>
<p>
	<%= link_to "Iotagive", "http://iotagive.com"%> 
	is a project to try to make giving more natural.
</p>

app/views/pages/home.html.erb
<% if user_signed_in? %>
	<h1>You're Logged In!</h1>
<% else %>	

<div class="hero-unit">
<h1>Welcome to Iotagive</h1>
<p>
	You've found the home page for the 
<%= link_to "Iotagive", "http://iotagive.com" %>
application.
</p>
<p>
	<%= link_to  "Sign Up Now!" , new_user_registration_path , class: "btn btn-primary btn-large" %>
</p>
</div>
<% end %>